"""
Django settings for paperwaves project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "0_tqywsmq1ls#fitr@5z=poushslei6zc_70x&mnakhs5mlhw#"
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG", default=0))

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = [
    host for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if host
]

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    "http://159.65.18.16:8080",
    "http://159.65.18.16:1337",
    "http://159.65.18.16",
    "http://radioreads.fun",
    "http://www.radioreads.fun",
    "https://radioreads.fun",
    "https://www.radioreads.fun",
]

# Use X-Forwarded-Host for CSRF checks
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# CORS settings (updated for django-cors-headers 4.x)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# Application definition

INSTALLED_APPS = [
    "scraper",
    "stations.apps.StationsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "django_celery_beat",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "PAGE_SIZE_QUERY_PARAM": "page_size",
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "paperwaves.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "paperwaves.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# PostgreSQL is required for consistency between dev and prod
# This prevents SQLite fallback issues and ensures migrations work predictably
SQL_ENGINE = os.environ.get("SQL_ENGINE")
if not SQL_ENGINE:
    raise ValueError(
        "SQL_ENGINE environment variable is required. "
        "Set it to 'django.db.backends.postgresql' in your .env file."
    )
if SQL_ENGINE != "django.db.backends.postgresql":
    raise ValueError(
        f"Only PostgreSQL is supported. Got SQL_ENGINE='{SQL_ENGINE}'. "
        "Please set SQL_ENGINE='django.db.backends.postgresql' in your .env file."
    )

SQL_DATABASE = os.environ.get("SQL_DATABASE")
SQL_USER = os.environ.get("SQL_USER")
SQL_PASSWORD = os.environ.get("SQL_PASSWORD")
SQL_HOST = os.environ.get("SQL_HOST")
SQL_PORT = os.environ.get("SQL_PORT", "5432")

if not all([SQL_DATABASE, SQL_USER, SQL_PASSWORD, SQL_HOST]):
    missing = [
        var
        for var, val in [
            ("SQL_DATABASE", SQL_DATABASE),
            ("SQL_USER", SQL_USER),
            ("SQL_PASSWORD", SQL_PASSWORD),
            ("SQL_HOST", SQL_HOST),
        ]
        if not val
    ]
    raise ValueError(
        f"Missing required database environment variables: {', '.join(missing)}. "
        "Please configure these in your .env file."
    )

DATABASES = {
    "default": {
        "ENGINE": SQL_ENGINE,
        "NAME": SQL_DATABASE,
        "USER": SQL_USER,
        "PASSWORD": SQL_PASSWORD,
        "HOST": SQL_HOST,
        "PORT": SQL_PORT,
    }
}

# Default primary key field type (required for Django 3.2+)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = "/static/"
STATIC_URL = "/staticfiles/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files (user-uploaded content like book covers)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Debug toolbar - IP addresses that can see the debug toolbar
# Configure via DEBUG_IP_ADDRESS environment variable (comma-separated)
INTERNAL_IPS = ["127.0.0.1"]
debug_ip_addresses = os.environ.get("DEBUG_IP_ADDRESS", "")
if debug_ip_addresses:
    INTERNAL_IPS.extend(
        [ip.strip() for ip in debug_ip_addresses.split(",") if ip.strip()]
    )

# CELERY STUFF
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379")
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = "Europe/London"

# Optional: Flower dashboard URL for admin "Open Flower" link (e.g. https://flower.example.com)
FLOWER_URL = os.environ.get("FLOWER_URL", "")

# Celery Beat Schedule
# Set PAUSE_SCRAPING=True in environment to disable scheduled scraping
PAUSE_SCRAPING = os.environ.get("PAUSE_SCRAPING", "False").lower() == "true"

CELERY_BEAT_SCHEDULE = {}
if not PAUSE_SCRAPING:
    CELERY_BEAT_SCHEDULE = {
        "scrape-all-brands-daily": {
            "task": "stations.tasks.scrape_all_brands",
            "schedule": crontab(hour=2, minute=0),  # Daily at 2 AM London time
        },
        "extract-books-every-30-minutes": {
            "task": "stations.tasks.extract_books_from_new_episodes",
            "schedule": crontab(minute="*/30"),  # Every 30 minutes
        },
    }

# AI / BOOK EXTRACTION
# Set to 'ai' to use Claude AI, 'keyword' for legacy keyword matching, 'both' for both
BOOK_EXTRACTION_MODE = os.environ.get("BOOK_EXTRACTION_MODE", "keyword")

# Bookshop.org Affiliate
BOOKSHOP_AFFILIATE_ID = os.environ.get("BOOKSHOP_AFFILIATE_ID", "16640")

# Logging configuration
# Enhanced logging for production debugging - captures all errors with stack traces
# Supports both console (Docker logs) and file-based logging (if directory is writable)
handlers_config = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "detailed" if DEBUG else "verbose",
    },
}

# Add file handler for production debugging (if directory is writable)
LOG_DIR = os.path.join(BASE_DIR, "logs")
try:
    os.makedirs(LOG_DIR, exist_ok=True)
    # Test if we can write to the directory
    test_file = os.path.join(LOG_DIR, ".test_write")
    with open(test_file, "w") as f:
        f.write("test")
    os.remove(test_file)
    # If we get here, directory is writable - add file handler
    handlers_config["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": os.path.join(LOG_DIR, "django.log"),
        "maxBytes": 1024 * 1024 * 10,  # 10MB
        "backupCount": 5,
        "formatter": "detailed" if DEBUG else "verbose",
    }
except (OSError, PermissionError):
    # Directory not writable or can't create - skip file logging
    # Console logging will still work
    pass

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "detailed": {
            "format": "{levelname} {asctime} {module} {funcName} {lineno} {process:d} {thread:d}\n{message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": handlers_config,
    "root": {
        "handlers": list(handlers_config.keys()),
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": list(handlers_config.keys()),
            "level": "INFO" if not DEBUG else "DEBUG",
            "propagate": False,
        },
        "django.request": {
            "handlers": list(handlers_config.keys()),
            "level": (
                "WARNING" if not DEBUG else "DEBUG"
            ),  # Changed from ERROR to WARNING to capture more
            "propagate": False,
        },
        "django.server": {
            "handlers": list(handlers_config.keys()),
            "level": "INFO" if not DEBUG else "DEBUG",
            "propagate": False,
        },
        "stations": {
            "handlers": list(handlers_config.keys()),
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "scraper": {
            "handlers": list(handlers_config.keys()),
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}
