# Generated by Django 3.0.5 on 2020-05-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20200428_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='pid',
            field=models.CharField(default='', max_length=120),
        ),
    ]
