# Generated by Django 3.0.5 on 2020-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_station_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='pid',
            new_name='station_id',
        ),
        migrations.AddField(
            model_name='brand',
            name='pid',
            field=models.CharField(default='', max_length=120),
        ),
    ]
