# Generated by Django 3.0.5 on 2020-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20200511_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
