# Generated by Django 3.0.5 on 2020-05-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_episode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stations.Brand'),
        ),
    ]
