# Generated by Django 3.0.5 on 2020-05-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_auto_20200512_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Brand'),
        ),
    ]
