# Generated by Django 3.0.5 on 2020-05-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_auto_20200512_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='pid',
        ),
    ]
