# Generated by Django 3.0.5 on 2020-05-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_remove_brand_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.URLField(default='', unique=True),
        ),
    ]
