# Generated by Django 3.0.5 on 2020-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_auto_20200515_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='hasBook',
            field=models.BooleanField(default=False),
        ),
    ]
