# Generated by Django 3.0.5 on 2020-05-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_episode_hasbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='hasBook',
            new_name='has_book',
        ),
    ]
