# Generated by Django 3.1a1 on 2020-05-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_auto_20200516_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.brand'),
        ),
    ]
