# Generated by Django 5.1.4 on 2025-11-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0018_book_author_episode_aired_at_episode_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
