# Generated by Django 5.1.4 on 2025-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0019_add_purchase_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]

