# Generated by Django 5.1.4 on 2025-11-25 11:47

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slugs for existing episodes"""
    Episode = apps.get_model("stations", "Episode")
    for episode in Episode.objects.all():
        if not episode.slug:
            base_slug = slugify(episode.title) or f"episode-{episode.id}"
            slug = base_slug
            counter = 1
            while Episode.objects.filter(slug=slug).exclude(pk=episode.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            episode.slug = slug
            episode.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0020_add_brand_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="ai_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="episode",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        # Add slug field without unique constraint first
        migrations.AddField(
            model_name="episode",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, db_index=False),
        ),
        # Populate slugs for existing episodes
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Now make it unique (this will create the index)
        migrations.AlterField(
            model_name="episode",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
