# Generated by Django 5.1.4 on 2025-11-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0021_episode_ai_description_episode_raw_data_episode_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='ai_description',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='raw_data',
        ),
        migrations.CreateModel(
            name='RawEpisodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_data', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='stations.episode')),
            ],
        ),
    ]
