# Generated by Django 5.1.4 on 2025-11-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0022_remove_episode_ai_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='description',
        ),
    ]
