# Generated by Django 5.1.4 on 2025-11-25 22:02

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slugs for existing books and brands"""
    Book = apps.get_model("stations", "Book")
    Brand = apps.get_model("stations", "Brand")

    # Populate book slugs
    for book in Book.objects.all():
        if not book.slug:
            base_slug = slugify(book.title) or f"book-{book.id}"
            slug = base_slug
            counter = 1
            while Book.objects.filter(slug=slug).exclude(pk=book.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            book.slug = slug
            book.save(update_fields=["slug"])

    # Populate brand slugs
    for brand in Brand.objects.all():
        if not brand.slug:
            base_slug = slugify(brand.name) or f"brand-{brand.id}"
            slug = base_slug
            counter = 1
            while Brand.objects.filter(slug=slug).exclude(pk=brand.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            brand.slug = slug
            brand.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0023_remove_episode_description'),
    ]

    operations = [
        # Add slug fields without unique constraint first
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, db_index=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, db_index=False),
        ),
        # Populate slugs for existing records
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Now make them unique
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
