# Generated by Django 5.1.4 on 2025-12-10 22:24

import stations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0024_add_slug_to_book_and_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.CharField(blank=True, default='', help_text='Short AI-generated teaser for homepage display', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_local',
            field=models.ImageField(blank=True, null=True, upload_to=stations.models.book_cover_path),
        ),
    ]
