# Generated by Django 5.1.4 on 2025-12-10 22:50

import stations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0025_book_blurb_book_cover_image_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image_local',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Book cover image stored locally', null=True, upload_to=stations.models.book_cover_path),
        ),
    ]
