# Generated by Django 5.1.4 on 2025-12-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0027_rename_blurb_to_micro_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='micro_synopsis',
        ),
    ]
