# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0029_rawepisodedata_extraction_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="scraped_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCRAPED", "Scraped"),
                    ("QUEUED", "Queued"),
                    ("PROCESSING", "Processing"),
                    ("PROCESSED", "Processed"),
                    ("FAILED", "Failed"),
                ],
                default="SCRAPED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="extraction_result",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
