# Generated by Django 5.1.4

from django.db import migrations


def truncate_episode_and_book(apps, schema_editor):
    """Truncate Book, RawEpisodeData, then Episode (drop all data)."""
    # Order: Book (FK Episode), RawEpisodeData (FK Episode), Episode
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "TRUNCATE TABLE stations_book, stations_rawepisodedata, "
            "stations_episode CASCADE"
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0030_add_episode_pipeline_fields"),
    ]

    operations = [
        migrations.RunPython(truncate_episode_and_book, noop),
        migrations.DeleteModel(
            name="RawEpisodeData",
        ),
    ]
