# Generated by Django 5.1.4 on 2026-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0031_drop_all_data_remove_rawepisodedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='google_books_verified',
            field=models.BooleanField(default=False),
        ),
    ]
