# Generated by Django 5.1.4 on 2026-02-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0032_add_book_confidence_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ai_confidence',
        ),
        migrations.AddField(
            model_name='episode',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
