# Generated by Django 5.1.4 on 2026-02-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0033_move_confidence_to_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_fetch_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
