# Generated by Django 5.1.4 on 2026-02-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0034_add_cover_fetch_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='review_status',
            field=models.CharField(blank=True, choices=[('', 'Unprocessed'), ('NOT_REQUIRED', 'Not required'), ('REQUIRED', 'Required'), ('REVIEWED', 'Reviewed')], default='', max_length=20),
        ),
    ]
