# Generated by Django 5.1.4 on 2026-02-22 21:45

from django.db import migrations


def backfill_review_status(apps, schema_editor):
    Episode = apps.get_model("stations", "Episode")
    Book = apps.get_model("stations", "Book")

    for episode in Episode.objects.filter(ai_confidence__isnull=False):
        if episode.ai_confidence < 0.9:
            episode.review_status = "REQUIRED"
        elif Book.objects.filter(episode=episode, google_books_verified=False).exists():
            episode.review_status = "REQUIRED"
        else:
            episode.review_status = "NOT_REQUIRED"
        episode.save(update_fields=["review_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0035_add_review_status"),
    ]

    operations = [
        migrations.RunPython(backfill_review_status, migrations.RunPython.noop),
    ]
