# Generated by Django 5.1.4 on 2026-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0042_remove_book_episode_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='spider_name',
            field=models.CharField(blank=True, default='bbc_episodes', max_length=120),
        ),
    ]
