# Generated by Django 5.1.4 on 2026-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0043_brand_spider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unmatched_categories',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
