# Generated by Django 5.1.4 on 2026-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0044_book_unmatched_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='producer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='brand',
            name='producer_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
