# Generated by Django 5.1.4 on 2026-03-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0049_episode_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name'], 'verbose_name_plural': 'topics'},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='has_book',
        ),
    ]
